### ISSUE TITLE
clicks confused by reference link context?

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/small-client-wiki#14]
Reference can go into a loop fetching from the wrong site when it knows the right site as demonstrated by the hover.  I've seen this in chrome when clicking "Pattern Language" on the right-most page here:
http://read.wiki.org/#c2.fed.wiki.org/welcome-visitors/c2.fed.wiki.org/topic-based-subsets/c2.fed.wiki.org/pattern-subsets

![image](https://cloud.githubusercontent.com/assets/12127/19495123/eacc8bf4-9536-11e6-8c05-35b96e52fd53.png)

**Comment by WardCunningham** [comment]
This may not be related to Reference. Our main page will put Firefox into a loop fetching the default page. 

http://read.wiki.org

See Tools>Web Developer>Web Console

**Comment by paul90** [comment]
Not seen the http://read.wiki.org/ problem with Firefox, but the "Pattern Language" loop happens with Firefox as well.

**Comment by paul90** [comment]
The looping appears to be caused by the response from c2.com site having a content-type of `text/plain` rather than `application/json`.

**Comment by WardCunningham** [comment]
This has been fixed, now several ways.
